### ISSUE TITLE
Support for ET Book

### ISSUE THREAD

**Issue by alech** [Tufte-LaTeX/tufte-latex#104]
Would it be possible to support ET Book?
http://edwardtufte.github.io/et-book/

**Comment by godbyk** [comment]
You can use it now if you compile with XeLaTeX. Try adding the following to the preamble of your document (after installing the fonts):

```
\usepackage{fontspec}
\setmainfont{ETBembo}[Mapping=TeX-text]
```

Depending on the font metrics, some adjustments may need to be made to the leading, measure, etc. to improve the appearance.

**Comment by alech** [comment]
Nice, will give it a try!
