### ISSUE TITLE
100 consecutive dead cycles error

### ISSUE THREAD

**Issue by alecshaw** [Tufte-LaTeX/tufte-latex#116]
I get an error when trying to add more than 24 margin notes which are meant to be positioned on the same page: `Output loop---100 consecutive dead cycles.`

I was able to resolve the issue by calling `\newpage` so that subsequent margin notes after the limit don't appear on the same page, but not wanting this page break in my document I looked for another solution. `\maxdeadcycles=200` has also solved this issue.

Is there a better way to be resolving this, or is this a bug to be looked into?

**Comment by godbyk** [comment]
You might see if `\FloatBarrier` flushes some of the margin notes. Use it between two paragraphs (as it causes a paragraph break).

I haven't seen this error before. Usually when there are a ton of margin notes per page, I see a `Too many unprocessed floats` message.

The complaint about too many consecutive dead cycles means that TeX looped over 100 times without outputting a new page.
