### ISSUE TITLE
Space between items in list of figures and list of tables is not constant

### ISSUE THREAD

**Issue by ls6** [Tufte-LaTeX/tufte-latex#118]
If you look at the list of tables of [sample-book.pdf](https://github.com/Tufte-LaTeX/tufte-latex/raw/master/sample-book.pdf) you can see that the spacing after table 3 gets bigger.

I've spotted a similar problem in my table of figures where I have 9 figures on the list and the first 6 have less space between them than the last 3. I've checked that it _does not_ depend in whether the caption fits in one line or not---if I make all of them short the issue is still there.

**Comment by godbyk** [comment]
If I remember correctly, they are grouped by chapter. Are the first six figures in the same chapter and each of the remaining in a chapter on their own?

**Comment by ls6** [comment]
They are!
So it is expected behaviour... although not obvious at all 😮 
Shall I close this issue?
